name: PR Hello World

on:
  pull_request:
    types: [opened]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Hello World を出力
        run: node -e "console.log('Hello, World!')"